### ISSUE TITLE
Error running `from iceflow.ui import IceFlowUI`

### ISSUE THREAD

**Issue by eeholmes** [nsidc/NSIDC-Data-Tutorials#31] opened 2021-12-28 00:27 UTC
Error seems to be with the loading of the BlueMarble base layer.
This code generates the error:
```
from iceflow.ui import IceFlowUI
```
run from the Binder instance of the notebooks.

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.9/site-packages/xyzservices/lib.py in __getattr__(self, key)
     41         try:
---> 42             return self.__getitem__(key)
     43         except KeyError:

KeyError: 'BlueMarble'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_96/3719722181.py in <module>
----> 1 from iceflow.ui import IceFlowUI

~/notebooks/iceflow/iceflow/ui.py in <module>
      7 from ipyleaflet import (Map, SearchControl, AwesomeIcon, GeoJSON,
      8                         Marker, DrawControl, LayersControl)
----> 9 from .layers import custom_layers, flight_layers, widget_projections
     10 from .client import IceflowClient
     11 

~/notebooks/iceflow/iceflow/layers.py in <module>
    101 widget_projections = {
    102     'global': {
--> 103         'base_map': basemaps.NASAGIBS.BlueMarble,
    104         'projection': projections.EPSG3857,
    105         'center': (30, -30),

/srv/conda/envs/notebook/lib/python3.9/site-packages/xyzservices/lib.py in __getattr__(self, key)
     42             return self.__getitem__(key)
     43         except KeyError:
---> 44             raise AttributeError(key)
     45 
     46     def __dir__(self):

AttributeError: BlueMarble
```

**Comment by betolink** [comment] 2021-12-28 04:47
Thanks for reporting this @eeholmes. The bug is caused by ipyleaflet, there is a major change on the latest version, the base layers it uses for the maps are organized in a different way. Fixing this tomorrow.

**Comment by asteiker** [comment] 2022-01-18 18:52
#33 Was just merged and verified through the Binder option. Please let us know if you still see any issues with the widget.

**Closed by asteiker** 2022-01-18 18:52 UTC
